### ISSUE TITLE
Please provide a simple example

### ISSUE THREAD

**Issue by benzwt** [Azure/warp-openssl#6]
I'm fairly new to warp.
I cannot write a simple program by referring the tests and doc.
Would you please write a simple main for us.

thanks!

**Comment by benzwt** [comment]
I have created a self-signed certificate for localhost.
However, I am getting **tlsv1 alert decode error** on my Linux machine with a .Net 6 app talking with the warp server. I believe that your work is a cure for this problem. thanks!

**Comment by benzwt** [comment]
``` rust
#[tokio::main]
async fn main() {
    use warp::Filter;

    // Match any request and return hello world!
    let routes = warp::any().map(|| "Hello, World!");

    warp::serve(routes)
        .tls()
        .cert_path("host.crt")
        .key_path("host.key")
        .run(([127, 0, 0, 1], 3030))
        .await;
}
``` 

I tried my best to convert the above code with 
warp-openssl, but I cannot compile it. 
Please shed some light.
thanks!

``` rust
use std::net::SocketAddr;
use warp_openssl::serve;
use tokio::sync::oneshot;

async fn main() -> Result<()> {
    let addr = SocketAddr::from(([127, 0, 0, 1], 3030));
    
    let (tx, rx) = oneshot::channel();
    let server = serve(warp::Filter::map(warp::any(), || "Hello, World!"))
        .key(include_bytes!("key.rsa").to_vec())
        .cert(include_bytes!("cert.pem").to_vec());

    let addr, server = server.bind_with_graceful_shutdown(addr, async move {
        rx.await.ok();
    })?;

    let server = tokio::spawn(async move {
        server.await;
    });
}

```

**Comment by msabansal** [comment]
Where do you get the error?  In the. Net app? You will have to accept cert by changing server certificate validation

**Comment by benzwt** [comment]
> Where do you get the error? In the. Net app? You will have to accept cert by changing server certificate validation

Net6.0 custom validation is not working on Linux machine.

**Comment by msabansal** [comment]
It turns out that TLS1.3 was disabled. I have added some tests and example server,client in this branch: https://github.com/Azure/warp-openssl/tree/tlssupport Please see if that works for you.

I need to follow up and think on the API to configure TLS settings before merging to main.

**Comment by msabansal** [comment]
Added a sample in example directory.
